version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://expense_user:expense_pass@db:5432/expense_db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=expense_db
      - POSTGRES_USER=expense_user
      - POSTGRES_PASSWORD=expense_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense_user -d expense_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data: 